-- 2026 탄소중립포인트 녹색생활실천 항목 마스터
-- 단가·단위: 탄소중립포인트 녹색생활실천 공식 인센티브 안내 기준
-- 항목별 상한은 팀 결정 C-10에 따라 확정 전까지 NULL로 둔다.

INSERT INTO greenlife_item (
    item_code, name, unit_price, reward_unit,
    monthly_cap_amount, annual_cap_amount, practice_steps,
    icon_key, standard_year, external_url, display_order, is_active
) VALUES
('E_RECEIPT', '전자영수증', 10, '건', NULL, NULL,
 JSON_ARRAY('참여기업 앱에서 전자영수증 발급을 설정해요', '종이영수증 대신 전자영수증을 받아요', '참여기업이 제출한 실적이 반영되면 포인트가 쌓여요'),
 'receipt', 2026, 'https://cpoint.or.kr/netzero/entGuide/nv_entGuideList.do', 1, 1),
('TUMBLER', '텀블러·다회용컵', 300, '개', NULL, NULL,
 JSON_ARRAY('참여 카페의 적립 방법을 확인해요', '일회용컵 대신 텀블러나 다회용컵을 선택해요', '결제할 때 참여 계정으로 실적을 적립해요'),
 'tumbler', 2026, 'https://cpoint.or.kr/netzero/entGuide/nv_entGuideList.do', 2, 1),
('CUP_RETURN', '일회용컵 반환', 100, '개', NULL, NULL,
 JSON_ARRAY('일회용컵 보증금 참여 매장을 확인해요', '사용한 일회용컵을 반납기에 반환해요', '참여 정보로 반환 실적을 적립해요'),
 'cup-return', 2026, 'https://cpoint.or.kr/netzero/entGuide/nv_entGuideList.do', 3, 1),
('REFILL_STATION', '리필스테이션', 500, '회', NULL, NULL,
 JSON_ARRAY('리필스테이션 참여 매장을 확인해요', '세제나 화장품을 담을 빈 용기를 가져가요', '매장에서 제품을 리필하고 실적을 적립해요'),
 'refill', 2026, 'https://cpoint.or.kr/netzero/entGuide/nv_entGuideList.do', 4, 1),
('REUSABLE_CONTAINER', '다회용기', 500, '회', NULL, NULL,
 JSON_ARRAY('다회용기 참여 배달 서비스를 확인해요', '주문할 때 다회용기 사용을 선택해요', '반납 안내에 따라 용기를 반납해요'),
 'container', 2026, 'https://cpoint.or.kr/netzero/entGuide/nv_entGuideList.do', 5, 1),
('ZERO_EMISSION_CAR', '무공해차 대여', 100, 'km', NULL, NULL,
 JSON_ARRAY('참여 차량공유업체 앱을 이용해요', '전기차나 수소차 등 무공해차를 대여해요', '차량 반납일을 기준으로 주행 실적을 확인해요'),
 'car', 2026, 'https://cpoint.or.kr/netzero/entGuide/nv_entGuideList.do', 6, 1),
('ECO_PRODUCT', '친환경제품 구매', 500, '건', NULL, NULL,
 JSON_ARRAY('참여 매장과 인정되는 친환경제품을 확인해요', '인정 기준에 맞는 제품을 2,000원 이상 구매해요', '그린카드 또는 참여기업 결제로 실적을 적립해요'),
 'eco', 2026, 'https://cpoint.or.kr/netzero/entGuide/nv_entGuideList.do', 7, 1),
('HIGH_QUALITY_RECYCLING', '고품질 재활용품 배출', 300, 'kg', NULL, NULL,
 JSON_ARRAY('지자체의 참여 수거점을 확인해요', '안내에 맞게 고품질 재활용품을 분리해요', '수거점에 배출하고 무게 실적을 확인해요'),
 'recycle', 2026, 'https://cpoint.or.kr/netzero/entGuide/nv_entGuideList.do', 8, 1),
('USED_PHONE', '폐휴대폰 반납', 1000, '개', NULL, NULL,
 JSON_ARRAY('폐휴대폰 참여 수거처를 확인해요', '사용하지 않는 휴대폰의 개인정보를 정리해요', '기부·재활용 참여기업에 휴대폰을 반납해요'),
 'phone', 2026, 'https://cpoint.or.kr/netzero/entGuide/nv_entGuideList.do', 9, 1),
('FUTURE_GENERATION', '미래세대실천행동', 0, '운영계획', NULL, NULL,
 JSON_ARRAY('기후행동 1.5℃ 앱에 가입해요', '앱에서 운영 중인 실천 프로그램에 참여해요', '프로그램 운영계획에 따라 포인트를 확인해요'),
 'future', 2026, 'https://c-action.kr', 10, 1),
('SHARED_BICYCLE', '공유자전거 이용', 100, 'km', NULL, NULL,
 JSON_ARRAY('참여 중인 공유자전거 서비스를 확인해요', '참여 계정으로 공유자전거를 대여해요', '이용을 종료하고 주행 실적을 확인해요'),
 'bicycle', 2026, 'https://cpoint.or.kr/netzero/entGuide/nv_entGuideList.do', 11, 1),
('ZERO_LEFTOVERS', '잔반제로 실천', 100, '회', NULL, NULL,
 JSON_ARRAY('잔반제로 참여 단체급식소를 확인해요', '먹을 만큼만 배식받아 식사해요', '잔반을 남기지 않고 참여 실적을 확인해요'),
 'zero-leftovers', 2026, 'https://cpoint.or.kr/netzero/entGuide/nv_entGuideList.do', 12, 1),
('TREE_PLANTING', '나무심기', 3000, '회', NULL, NULL,
 JSON_ARRAY('공공기관·기업·단체의 참여 캠페인을 확인해요', '안내된 일정과 장소에서 나무심기에 참여해요', '주최 기관이 제출한 참여 실적을 확인해요'),
 'tree', 2026, 'https://cpoint.or.kr/netzero/entGuide/nv_entGuideList.do', 13, 1),
('BALCONY_SOLAR', '가정용 베란다 태양광 설치', 10000, '회', NULL, NULL,
 JSON_ARRAY('참여 가능한 베란다 태양광 사업을 확인해요', '일반 가정의 베란다에 미니태양광 설비를 설치해요', '설치 완료 후 참여 실적을 확인해요'),
 'solar', 2026, 'https://cpoint.or.kr/netzero/entGuide/nv_entGuideList.do', 14, 1),
('RECYCLED_MATERIAL_PRODUCT', '재생원료 사용제품 구매', 100, '건', NULL, NULL,
 JSON_ARRAY('재생원료 사용비율 표시 승인 제품을 확인해요', '참여 매장에서 승인 제품을 구매해요', '참여기업이 제출한 구매 실적을 확인해요'),
 'recycled-product', 2026, 'https://cpoint.or.kr/netzero/entGuide/nv_entGuideList.do', 15, 1),
('SHOPPING_BAG', '장바구니 이용', 50, '회', NULL, NULL,
 JSON_ARRAY('장바구니 참여 오프라인 매장을 확인해요', '비닐·종이봉투 대신 다회용 장바구니를 사용해요', '결제할 때 장바구니 이용 실적을 적립해요'),
 'shopping-bag', 2026, 'https://cpoint.or.kr/netzero/entGuide/nv_entGuideList.do', 16, 1),
('PERSONAL_CONTAINER', '개인용기 식품 포장', 500, '회', NULL, NULL,
 JSON_ARRAY('개인용기 포장 참여 매장을 확인해요', '깨끗한 다회용 개인용기를 가져가요', '식품 구매·포장 시 개인용기를 사용해요'),
 'personal-container', 2026, 'https://cpoint.or.kr/netzero/entGuide/nv_entGuideList.do', 17, 1)
ON DUPLICATE KEY UPDATE
    name = VALUES(name),
    unit_price = VALUES(unit_price),
    reward_unit = VALUES(reward_unit),
    monthly_cap_amount = VALUES(monthly_cap_amount),
    annual_cap_amount = VALUES(annual_cap_amount),
    practice_steps = VALUES(practice_steps),
    icon_key = VALUES(icon_key),
    standard_year = VALUES(standard_year),
    external_url = VALUES(external_url),
    display_order = VALUES(display_order),
    is_active = VALUES(is_active),
    updated_at = CURRENT_TIMESTAMP;
