-- GreenPocket 실천 미션 카탈로그
-- 공식 근거:
--   한국에너지공단 에어컨 절약노하우: https://eep.energy.or.kr/more/knowhow4.aspx
--   산업통상자원부·한국에너지공단 하루 1kWh 줄이기: https://www.energy.or.kr/front/board/View21.do?boardMngNo=21&boardNo=10000653
--   한국에너지공단 가정용 가스보일러 절약노하우: https://eep.energy.or.kr/more/knowhow6.aspx
--   산업통상자원부·한국에너지공단 겨울철 난방비 절약: https://www.energy.or.kr/front/board/View21.do?boardMngNo=21&boardNo=10000670
--   한국에너지공단 난방비 절약 실천요령: https://min24.energy.or.kr/consult/info/view4.do
--   기후행동 실천포털 생활실천 안내서: https://www.gihoo.or.kr/menu.es?mid=a11302000000
--   서울특별시 서울물연구원 생활 절수: https://arisu.seoul.go.kr/arisu_center/center16/seoulWater/201512/sub0702.html
--
-- evidence_amount는 월 절감 사용량이다. 일·회당 공식 수치는 calculation_basis의
-- 명시된 데모 가정으로 월 환산한다. 가스 비율 근거는 한국에너지공단의 월 난방 기준
-- 141.7m3에 적용해 사용량으로 환산하고, 원래 비율을 rate_cap으로 보존한다.
-- 난이도는 비용이나 주거 설비 변경이 아니라 한 달 동안 반복해야 하는 습관 변화의
-- 강도로 구분한다. 세입자가 직접 하기 어려운 공사·교체·전문 청소 미션은 제공하지 않는다.

INSERT INTO mission_catalog (
    mission_code, utility_type, title, description, difficulty,
    evidence_amount, evidence_unit, evidence_text, calculation_basis,
    source_org, device_group, season_tags, rate_cap, display_order, is_active
) VALUES
-- 전기 12개
('ELEC_AC_TEMP_26', 'ELECTRICITY', '냉방 온도 26℃로 맞추기',
 '실내 적정온도를 지키면서 냉방 전력을 줄여요', 'EASY',
 12.300, 'kWh', '1℃당 냉방 전력 7% · 하루 0.41kWh',
 '에어컨 설정온도를 1℃ 높이고 26℃를 유지할 때 하루 0.41kWh 절감 · 0.41kWh × 30일 = 월 12.3kWh · 출처 절감률 7%를 상한으로 적용',
 '산업통상자원부·한국에너지공단', '냉방', 'SUMMER', 7.000, 10, 1),
('ELEC_AC_HOUR_1', 'ELECTRICITY', '에어컨 하루 1시간 줄이기',
 '켜 두는 시간을 하루 한 시간만 줄여요', 'NORMAL',
 40.000, 'kWh', '월 40kWh · 4,880원',
 '15평형 에어컨 소비전력 2kW · 하루 1시간 · 월 20일 절약 기준',
 '한국에너지공단', '냉방', 'SUMMER', 30.000, 20, 1),
('ELEC_AC_HOUR_2', 'ELECTRICITY', '에어컨 하루 2시간 줄이기',
 '목표가 부족할 때 냉방 시간을 두 시간 줄여요', 'HARD',
 80.000, 'kWh', '월 80kWh · 1시간 실천의 2배',
 '공식 1시간 절감량 40kWh를 동일 조건에서 2시간으로 선형 환산한 추정값 · 40kWh × 2 = 월 80kWh',
 '한국에너지공단', '냉방', 'SUMMER', 30.000, 30, 1),
('ELEC_AC_USE_FAN', 'ELECTRICITY', '에어컨 대신 선풍기 사용하기',
 '가능한 시간에는 선풍기로 냉방을 대신해요', 'HARD',
 120.000, 'kWh', '월 120kWh · 14,640원',
 '15평형 에어컨과 선풍기 소비전력 차이 1.5kW · 하루 4시간 · 월 20일 기준',
 '한국에너지공단', '냉방', 'SUMMER', 30.000, 40, 1),
('ELEC_AC_FILTER', 'ELECTRICITY', '에어컨 필터 청소하기',
 '2주에 한 번 필터를 청소해 냉방 효율을 지켜요', 'EASY',
 10.700, 'kWh', '필터 청소 여부에 따라 월 10.7kWh 차이',
 '필터 미청소 시 소비전력이 평균 3~5% 증가하며 월 1~2회 청소 여부의 월간 소비전력 차이는 10.7kWh',
 '한국에너지공단', '냉방', 'SUMMER', 30.000, 50, 1),
('ELEC_LIGHTS_OFF', 'ELECTRICITY', '사용하지 않는 조명 끄기',
 '빈 방의 조명을 바로 꺼요', 'EASY',
 10.800, 'kWh', '하루 0.36kWh · 월 10.8kWh',
 '사용하지 않는 조명 소등 시 하루 0.36kWh 절감 · 0.36kWh × 30일 = 월 10.8kWh',
 '산업통상자원부·한국에너지공단', '조명', 'SPRING,SUMMER,AUTUMN,WINTER', 30.000, 60, 1),
('ELEC_UNPLUG', 'ELECTRICITY', '사용하지 않는 플러그 뽑기',
 '대기전력이 생기는 전자제품의 플러그를 뽑아요', 'EASY',
 9.600, 'kWh', '하루 0.32kWh · 월 9.6kWh',
 '사용하지 않는 전자제품 플러그를 뽑을 때 하루 0.32kWh 절감 · 0.32kWh × 30일 = 월 9.6kWh',
 '산업통상자원부·한국에너지공단', '대기전력', 'SPRING,SUMMER,AUTUMN,WINTER', 30.000, 70, 1),
('ELEC_LAUNDRY_BATCH', 'ELECTRICITY', '세탁물 모아서 세탁하기',
 '적은 양을 자주 돌리지 않고 한 번에 세탁해요', 'EASY',
 2.700, 'kWh', '하루 환산 0.09kWh · 월 2.7kWh',
 '세탁물을 모아서 세탁할 때 하루 환산 0.09kWh 절감 · 0.09kWh × 30일 = 월 2.7kWh',
 '산업통상자원부·한국에너지공단', '세탁', 'SPRING,SUMMER,AUTUMN,WINTER', 30.000, 80, 1),
('ELEC_RICE_KEEP_WARM', 'ELECTRICITY', '전기밥솥 보온시간 줄이기',
 '먹을 만큼만 보온하고 남은 밥은 냉동 보관해요', 'EASY',
 1.800, 'kWh', '하루 환산 0.06kWh · 월 1.8kWh',
 '전기밥솥 보온시간을 줄일 때 하루 환산 0.06kWh 절감 · 0.06kWh × 30일 = 월 1.8kWh',
 '산업통상자원부·한국에너지공단', '밥솥', 'SPRING,SUMMER,AUTUMN,WINTER', 30.000, 90, 1),
('ELEC_MICROWAVE_NATURAL_THAW', 'ELECTRICITY', '전자레인지 쓰기 전 자연해동하기',
 '냉동식품을 미리 냉장실로 옮겨 해동 시간을 줄여요', 'NORMAL',
 5.700, 'kWh', '자연해동 후 전자레인지 사용 시 하루 0.19kWh 절감',
 '공식 하루 절감량 0.19kWh × 30일 = 월 5.7kWh · 미리 옮겨 두는 준비가 필요한 반복 습관',
 '산업통상자원부·한국에너지공단', '전자레인지', 'SPRING,SUMMER,AUTUMN,WINTER', 30.000, 100, 1),
('ELEC_BIDET_HEAT_OFF', 'ELECTRICITY', '비데 온열 기능 끄기',
 '따뜻한 계절에는 변좌와 온수 기능을 꺼둬요', 'EASY',
 3.000, 'kWh', '비데 온열 기능을 끄면 하루 0.1kWh 절감',
 '공식 하루 절감량 0.1kWh × 30일 = 월 3.0kWh · 비데가 있는 집에서만 선택',
 '산업통상자원부·한국에너지공단', '비데', 'SPRING,SUMMER,AUTUMN', 30.000, 110, 1),
('ELEC_HEATER_HOUR_1', 'ELECTRICITY', '전기난방기 하루 1시간 줄이기',
 '전기장판과 온풍기는 꼭 필요한 시간만 사용해요', 'HARD',
 20.000, 'kWh', '1kW 난방기 사용을 하루 1시간씩 월 20일 단축하면 20kWh 절감',
 '공식 1kW 전기난방기 하루 4시간 × 월 20일 조건을 하루 1시간 단축으로 선형 환산 · 1kW × 1시간 × 20일 = 월 20kWh · 데모 환산 추정',
 '한국에너지공단', '전기난방', 'WINTER', 30.000, 120, 1),

-- 도시가스 10개
('GAS_HEATING_20', 'GAS', '실내 난방 20℃ 유지하기',
 '겨울철 적정 실내온도를 유지해요', 'EASY',
 7.794, 'm3', '한 달 가스 사용량 5.5% 절감',
 '공식 월 난방 기준 141.7m3 × 5.5% = 월 7.794m3 환산 · 출처 절감률 5.5%를 상한으로 적용',
 '산업통상자원부·한국에너지공단', '난방온도', 'WINTER', 5.500, 110, 1),
('GAS_HEATING_LOWER_1', 'GAS', '난방 설정온도 1℃ 더 낮추기',
 '목표가 부족할 때 현재 설정에서 한 도 더 낮춰요', 'NORMAL',
 9.919, 'm3', '난방온도 1℃를 낮추면 에너지 7% 절감',
 '공식 월 난방 기준 141.7m3 × 7% = 월 9.919m3 환산 · 출처 절감률 7%를 상한으로 적용',
 '한국에너지공단', '난방온도', 'WINTER', 7.000, 120, 1),
('GAS_HEATING_LOWER_2', 'GAS', '난방 설정온도 2℃ 더 낮추기',
 '두꺼운 옷과 담요를 함께 활용해 두 도 낮춰요', 'HARD',
 18.279, 'm3', '난방 설정온도 2℃ 하향 시 12.9% 절감',
 '공식 월 난방 기준 141.7m3 × 12.9% = 월 18.279m3 환산 · 출처 절감률 12.9%를 상한으로 적용',
 '기후에너지환경부', '난방온도', 'WINTER', 12.900, 130, 1),
('GAS_WARM_CLOTHES_LOWER_1', 'GAS', '내복 입고 난방 1℃ 낮추기',
 '내복이나 수면양말을 입고 설정온도를 한 도 낮춰요', 'NORMAL',
 9.919, 'm3', '난방온도 1℃를 낮추면 에너지 7% 절감',
 '공식 월 난방 기준 141.7m3 × 7% = 월 9.919m3 환산 · 의복은 체감온도를 보완하는 행동이며 합계는 1℃ 하향 효과만 반영',
 '한국에너지공단', '난방온도', 'WINTER', 7.000, 140, 1),
('GAS_SHOWER_WATER_OFF_2', 'GAS', '비누칠할 때 온수 2분 잠그기',
 '비누칠과 샴푸 중에는 온수를 잠깐 잠가요', 'EASY',
 4.081, 'm3', '샤워 5분 단축 효과의 2/5 · 월 4.081m3',
 '공식 5분 단축 절감량 10.202m3를 같은 유량의 2분으로 선형 환산 · 10.202m3 × 2 ÷ 5 = 월 4.081m3 · 데모 환산 추정',
 '산업통상자원부·한국에너지공단', '온수사용시간', 'SPRING,SUMMER,AUTUMN,WINTER', 2.880, 150, 1),
('GAS_SHOWER_MINUS_3', 'GAS', '샤워시간 3분 줄이기',
 '평소 샤워 시간을 세 분 줄여요', 'NORMAL',
 6.121, 'm3', '샤워 5분 단축 효과의 3/5 · 월 6.121m3',
 '공식 5분 단축 절감량 10.202m3를 같은 유량의 3분으로 선형 환산 · 10.202m3 × 3 ÷ 5 = 월 6.121m3 · 데모 환산 추정',
 '산업통상자원부·한국에너지공단', '온수사용시간', 'SPRING,SUMMER,AUTUMN,WINTER', 4.320, 160, 1),
('GAS_SHOWER_MINUS_5', 'GAS', '샤워시간 5분 줄이기',
 '목표가 높을 때 온수 사용 시간을 다섯 분 줄여요', 'HARD',
 10.202, 'm3', '한 달 가스 사용량 7.2% 절감',
 '공식 월 난방 기준 141.7m3 × 7.2% = 월 10.202m3 환산 · 출처 절감률 7.2%를 상한으로 적용',
 '산업통상자원부·한국에너지공단', '온수사용시간', 'SPRING,SUMMER,AUTUMN,WINTER', 7.200, 170, 1),
('GAS_WINDOW_CURTAIN', 'GAS', '해 지면 두꺼운 커튼 닫기',
 '밤에는 커튼을 닫아 창문으로 빠지는 열을 줄여요', 'EASY',
 7.794, 'm3', '한 달 가스 사용량 5.5% 절감',
 '에어캡·문풍지·커튼 활용의 공식 합산 효과를 대표값으로 사용 · 월 난방 기준 141.7m3 × 5.5% = 월 7.794m3 · 같은 단열 그룹은 하나만 합산',
 '산업통상자원부·한국에너지공단', '창문단열', 'AUTUMN,WINTER', 5.500, 180, 1),
('GAS_WINDOW_DAY_NIGHT', 'GAS', '낮에는 커튼 열고 밤에는 닫기',
 '낮에는 햇빛을 받고 해가 지면 커튼을 닫아요', 'NORMAL',
 7.794, 'm3', '문풍지·커튼 활용 시 한 달 5.5% 절감',
 '에어캡·문풍지·커튼 활용의 공식 합산 효과를 대표값으로 사용 · 낮과 밤에 커튼을 조절하는 데모 행동으로 환산 · 월 난방 기준 141.7m3 × 5.5% = 월 7.794m3 · 같은 단열 그룹은 하나만 합산',
 '산업통상자원부·한국에너지공단', '창문단열', 'AUTUMN,WINTER', 5.500, 190, 1),
('GAS_UNUSED_ROOM_HEATING', 'GAS', '안 쓰는 방 난방 끄고 문 닫기',
 '방별 조절이 가능한 집에서는 빈방 난방을 끄고 문을 닫아요', 'NORMAL',
 6.235, 'm3', '한 달 가스 사용량 4.4% 절감',
 '공식 월 난방 기준 141.7m3 × 4.4% = 월 6.235m3 환산 · 출처 절감률 4.4%를 상한으로 적용 · 원룸 등 방별 조절이 불가능하면 선택하지 않음',
 '산업통상자원부·한국에너지공단', '난방분배', 'WINTER', 4.400, 200, 1),

-- 수도 12개
('WATER_BRUSH_CUP', 'WATER', '양치할 때 컵 사용하기',
 '물을 계속 틀어두지 않고 컵에 받아 사용해요', 'EASY',
 0.300, 'm3', '4인 가족 하루 40L · 1인 기준 월 0.3m3',
 '4인 가족이 하루 40L를 절약하는 공식 수치를 1인 하루 10L로 환산 · 10L × 30일 = 월 300L',
 '서울특별시 서울물연구원', '양치', 'SPRING,SUMMER,AUTUMN,WINTER', 20.000, 210, 1),
('WATER_WASH_FACE_BASIN', 'WATER', '세수할 때 물 받아 쓰기',
 '세면대 물을 계속 틀지 않고 필요한 만큼 받아 써요', 'EASY',
 0.300, 'm3', '흐르는 물 1분을 줄이면 하루 약 10L 절수',
 '공식 설거지 유량 10분 100L를 1분 10L로 환산하고 세수할 때 하루 1분 흐르는 물을 줄이는 데모 가정 · 10L × 30일 = 월 300L',
 '기후에너지환경부·서울특별시 서울물연구원', '세면', 'SPRING,SUMMER,AUTUMN,WINTER', 20.000, 220, 1),
('WATER_SHOWER_MINUS_2', 'WATER', '샤워시간 2분 줄이기',
 '샤워 시간을 두 분만 줄여요', 'EASY',
 0.720, 'm3', '한 번에 24L · 매일 실천 시 월 0.72m3',
 '샤워시간 2분 단축 시 1회 24L 절약 · 하루 1회 × 30일 = 월 720L',
 '서울특별시 서울물연구원', '샤워', 'SPRING,SUMMER,AUTUMN,WINTER', 20.000, 230, 1),
('WATER_SHOWER_WATER_OFF_2', 'WATER', '비누칠할 때 물 2분 잠그기',
 '비누칠과 샴푸 중에는 샤워기 물을 잠깐 잠가요', 'NORMAL',
 0.720, 'm3', '샤워 2분 단축과 같은 월 0.72m3 절수',
 '샤워 중 물을 잠그는 공식 실천법에 2분 단축 공식 절감량 24L를 적용 · 24L × 하루 1회 × 30일 = 월 720L · 데모 환산 추정',
 '기후에너지환경부·서울특별시 서울물연구원', '샤워', 'SPRING,SUMMER,AUTUMN,WINTER', 20.000, 240, 1),
('WATER_SHOWER_MINUS_4', 'WATER', '샤워시간 4분 줄이기',
 '목표가 높을 때 샤워 시간을 네 분 줄여요', 'HARD',
 1.440, 'm3', '한 번에 48L · 2분 실천의 2배',
 '공식 2분 절감량 24L를 동일 조건에서 4분으로 선형 환산 · 48L × 하루 1회 × 30일 = 월 1,440L',
 '서울특별시 서울물연구원', '샤워', 'SPRING,SUMMER,AUTUMN,WINTER', 20.000, 250, 1),
('WATER_DISH_BASIN', 'WATER', '설거지통에 물 받아서 하기',
 '물을 계속 틀지 않고 설거지통을 사용해요', 'EASY',
 1.800, 'm3', '설거지통 사용 시 60% 절수',
 '흐르는 물 10분에 100L 이상 사용하는 공식 조건에 60% 절수율을 보수 적용 · 60L × 하루 1회 × 30일 = 월 1,800L',
 '서울특별시 서울물연구원', '설거지', 'SPRING,SUMMER,AUTUMN,WINTER', 20.000, 260, 1),
('WATER_DISH_WIPE_FIRST', 'WATER', '기름 묻은 그릇 먼저 닦기',
 '휴지나 스크레이퍼로 기름을 먼저 걷어낸 뒤 설거지해요', 'NORMAL',
 0.300, 'm3', '흐르는 물 1분 단축 가정 · 월 0.3m3',
 '기름 묻은 용기를 먼저 닦으라는 공식 실천법과 공식 설거지 유량 10분 100L를 결합 · 하루 1분 단축 가정 × 30일 = 월 300L · 데모 환산 추정',
 '기후에너지환경부·서울특별시 서울물연구원', '설거지', 'SPRING,SUMMER,AUTUMN,WINTER', 20.000, 270, 1),
('WATER_PRODUCE_BASIN', 'WATER', '채소와 과일 물 받아 씻기',
 '볼에 물을 받아 한꺼번에 씻고 마지막에만 헹궈요', 'NORMAL',
 0.720, 'm3', '물 받아 씻기 1회 60L 절수 가정 · 월 0.72m3',
 '과일·채소는 물 받아 씻으라는 공식 실천법에 설거지통 60% 절수의 보수값 60L를 적용 · 월 12회 = 월 720L · 데모 환산 추정',
 '기후에너지환경부·한국환경공단', '채소세척', 'SPRING,SUMMER,AUTUMN,WINTER', 20.000, 280, 1),
('WATER_LAUNDRY_BATCH', 'WATER', '세탁물 모아 주 1회 덜 돌리기',
 '적은 양을 자주 돌리지 않고 세탁물을 모아 빨아요', 'EASY',
 0.600, 'm3', '빨래 모아 빨기 30% 절수 · 월 4회 감축 가정',
 '공식 빨래 모아 빨기 30% 절수 행동에 수위 조절 최대 절수량 150L를 보수 적용 · 월 4회 덜 돌리기 = 월 600L · 데모 환산 추정',
 '서울특별시 서울물연구원', '세탁횟수', 'SPRING,SUMMER,AUTUMN,WINTER', 20.000, 290, 1),
('WATER_WASHER_LEVEL', 'WATER', '세탁기 수위를 알맞게 맞추기',
 '세탁물 양에 맞는 용량과 수위를 매번 선택해요', 'NORMAL',
 0.600, 'm3', '수위 조절 시 한 번에 최대 150L 절수',
 '공식 최대 절수량 150L × 월 4회 실천 = 월 600L · 세탁 횟수는 1인 데모 가정',
 '서울특별시 서울물연구원', '세탁설정', 'SPRING,SUMMER,AUTUMN,WINTER', 20.000, 300, 1),
('WATER_NO_EXTRA_RINSE', 'WATER', '세탁기 추가 헹굼 끄기',
 '세탁기 기본 헹굼 횟수만 사용해요', 'NORMAL',
 0.300, 'm3', '불필요한 추가 헹굼 생략 · 월 0.3m3 가정',
 '공식 자료의 추가 헹굼 불필요 안내와 수위 조절 최대 절수량 150L를 기준으로 회당 75L × 월 4회 = 월 300L · 데모 환산 추정',
 '서울특별시 서울물연구원', '세탁헹굼', 'SPRING,SUMMER,AUTUMN,WINTER', 20.000, 310, 1),
('WATER_REUSE_RINSE', 'WATER', '마지막 헹굼물 청소에 다시 쓰기',
 '받아 둔 마지막 헹굼물을 바닥이나 욕실 청소에 써요', 'HARD',
 0.600, 'm3', '마지막 헹굼물 재이용 · 월 0.6m3 가정',
 '공식 마지막 헹굼물 재이용 권고와 수위 조절 최대 절수량 150L를 기준으로 월 4회 재이용 = 월 600L · 데모 환산 추정',
 '서울특별시 서울물연구원', '세탁헹굼', 'SPRING,SUMMER,AUTUMN,WINTER', 20.000, 320, 1)
ON DUPLICATE KEY UPDATE
    utility_type = VALUES(utility_type),
    title = VALUES(title),
    description = VALUES(description),
    difficulty = VALUES(difficulty),
    evidence_amount = VALUES(evidence_amount),
    evidence_unit = VALUES(evidence_unit),
    evidence_text = VALUES(evidence_text),
    calculation_basis = VALUES(calculation_basis),
    source_org = VALUES(source_org),
    device_group = VALUES(device_group),
    season_tags = VALUES(season_tags),
    rate_cap = VALUES(rate_cap),
    display_order = VALUES(display_order),
    is_active = VALUES(is_active),
    updated_at = CURRENT_TIMESTAMP;

-- 기존 DB에 이미 들어간 세입자 부적합 미션은 이력 보존을 위해 삭제하지 않고 신규 노출만 중단한다.
UPDATE mission_catalog
SET is_active = 0,
    updated_at = CURRENT_TIMESTAMP
WHERE mission_code = 'GAS_PIPE_CLEAN'
   OR mission_code = 'GAS_HIGH_EFF_BOILER'
   OR mission_code = 'GAS_HOT_WATER_40'
   OR mission_code = 'GAS_WINDOW_INSULATION'
   OR mission_code = 'GAS_WINDOW_GAP'
   OR mission_code = 'GAS_UNUSED_ROOM_VALVE'
   OR mission_code = 'WATER_SAVING_SHOWER_HEAD'
   OR mission_code = 'WATER_FAUCET_AERATOR'
   OR mission_code = 'WATER_TOILET_SAVER'
   OR mission_code = 'WATER_EFFICIENT_TOILET';
