spring:
  application:
    name: greenpocket-backend

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 11MB

clova:
  ocr:
    invoke-url: ${CLOVA_OCR_INVOKE_URL:}
    secret: ${CLOVA_OCR_SECRET:}
    template-id: ${CLOVA_OCR_TEMPLATE_ID:}

server:
  port: ${SERVER_PORT:8080}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
