package com.greenpocket.profile.entity;

public enum EducationStatus {
	BELOW_HIGH_SCHOOL,
	HIGH_SCHOOL_STUDENT,
	HIGH_SCHOOL_EXPECTED_GRADUATION,
	HIGH_SCHOOL_GRADUATE,
	UNIVERSITY_STUDENT,
	UNIVERSITY_EXPECTED_GRADUATION,
	UNIVERSITY_GRADUATE,
	GRADUATE_SCHOOL,
	OTHER
}
